@url = http://localhost:5000
@storyId = 9e73e1f8-bff1-4a37-9e09-5a4d64a1dd69

###
GET {{url}}

###
POST {{url}}/stories

{
  "title": "Story 2",
  "text": "Lorem ipsum2",
  "author": "user1",
  "tags": ["tag12", "tag22"]
}

###
GET {{url}}/api/stories

###
GET {{url}}/api/stories/{{storyId}}

###
POST {{url}}/api/stories
Content-Type: application/json

{
  "title": "Story 1",
  "text": "Lorem ipsum",
  "author": "user1",
  "tags": ["tag1", "tag2"]
}


###
# @name sign_in
POST {{url}}/sign-in
Content-Type: application/json

{
}

@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}

###
GET {{url}}/secret
Authorization: Bearer {{accessToken}}

###
GET http://localhost:5010/secrets
Authorization: Bearer {{accessToken}}
